name: SPA CI

on:
  push:
    branch: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm install # instalar dependencias update
      - run: npm run build
